---
title: Limitations
---

Beyond the  [limitations of lavaan](https://lavaan.ugent.be/tutorial/before.html), some  features are not available (yet) in `lavaangui`:
    
- Support for variable types other than continuous
- Likelihood ratio tests for model comparison
- Multi-group models
- [Defined parameters](https://lavaan.ugent.be/tutorial/mediation.html)

We hope to add these features to `lavaangui` in the future. In case you need these features right away, we can recommend the following alternatives
    
- Create the model in `lavaangui`, export the script and use `lavaan` directly in R.
- Use [Onyx](https://onyx-sem.com/) instead. This is an alternative graphical structural equation modeling package, offering most of these features. The main downsides compared to `lavaangui` is that it is external standalone software requiring administrator privileges to be installed on most computers, and is not optimized for `lavaan`.
- If you are looking for an alternative for plotting (`plot_interactive`), consider using [semPlot](https://cran.r-project.org/web/packages/semPlot/index.html), [lavaanPlot](https://cran.r-project.org/web/packages/lavaanPlot/vignettes/Intro_to_lavaanPlot.html), or [tidySEM](https://cjvanlissa.github.io/tidySEM/).  The main downside is that the created visualizations are not interactive. The main upside is that it is easier to make to the creation of diagrams more reproducible.

The `lavaangui` package is free open-source software. This means (among other things) that there is no warranty whatsoever. On the other hand, you can verify the source code yourself: <https://github.com/karchjd/lavaangui/>