---
title: Means
---

By and large, structural equation models are used to model the covariance matrix of the observed variables in a dataset. But in some applications, it is useful to bring in the means of the observed variables too. One way to do this is to simply a constant variable in the model. A typical example would be the growth model shown below XXX.


Another alternative, in graphicalLavaan is to ask graphicalLavaan to automatically add means to the model. This can be done by going to Mean Options-> Model Means? and selecting Yes. Afterwards the two other menu options in Mean Options can be used to decide what means should be added to the model. Again also for this case, we recommend using Show Full model to ensure that graphicalLavaan does the thing you intended. 

The Add intercepts menu options also can have an effect when model means is set an automatic. In automatic lavaan decides whether to include models or not based on the model. On important case is when the model contains a constant variable, in which means are added to the model and the Add intercept options will have an effect. Again, also check the Full Model before fitting any model.

The mean status bar in the top toolboar always informs you whether means are being modeled or not.

