---
title: Model Specification
---

```{r echo=FALSE, message=FALSE}
library(lavaan)
```

## Overview

As is typical in latent variable modeling, a model is specified by creating a set of nodes, which represent the variables, and connecting those with arrows, which represent the hypothesized relationships between the variables.

## Creating Variables/Nodes

`lavaangui` supports the 3 types of variables typically contained in a SEM: observed variables, latent variables, and the constant variable, represented as square, circle, or triangle, respectively. 

There are three ways to create variables

1. Drag and drop the respective symbol from the `Top Toolbox` onto the `Model Window`. 
2. Right-clicking at any empty space within the `Model Window` and selecting the desired variable type from the context menu. This will create a corresponding variable at the cursor location.
3. Pressing either, "o" (observed variable), "l" (latent variable), or "c" (constant) variable, while hovering with the mouse over the `Model Window`. This also creates a corresponding variable at the cursor location.

## Linking Variables to Data

To fit a model, all observed variables must be linked to a variable in the data set. To link an observed variable node, give it the name of a variable in your data. This can be achieved by right-clicking the respective variable node and, selecting `Rename Variable` and then selecting from the variable names in the data set. After successfully linking a variable to a column in your data, you will get a success message in the `Message Area` and the border of the variable will become black, instead of grey.

## Arrows

Regression relationships between variables are represented by directed arrows, whereas variances and covariance relationships are represented by undirected arrows. To draw a direct arrow, press and hold the `CTRL` key and drag the mouse from one variable (the start of the arrow) to another (the end of the arrow). If you hold the `SHIFT` instead of the `CTRL` key, you create an undirected arrow instead.

The context menu of an arrow, reachable by right-clicking on the arrow, contains arrow-related operations: You can decide whether the path coefficient should be fixed  (`Fix Parameter`), declare a parameter to be freely estimated (`Free Parameter`) or force it to be estimated (`Force Free Parameter`). Visually a free arrow is displayed as a normal arrow, a fixed arrow contains *\@x* as the label, where *x* is the value it is fixed to, and a "forced free" arrow is blue. The difference between a free parameter and a "forced free" parameter is that the latter prevents `lavaan` from fixing the parameter, as would for example be the case if the parameter would correspond to the first loading of a latent factor. You can also revert the direction of an arrow (`Revert Direction`), set a directed arrow to undirected (`Set Undirected`), or set an undirected arrow to directed (`Set Directed`). Another important operation is to give a path coefficient a label, which is reachable via `Add/Change Label`. Two path coefficients with the same label will be constrained to be equal during estimation.

## Changing Model Appearance

You can drag variables around with the mouse to change the appearance of your model. For more advanced features, see [Apperance](./appearance.qmd).

## Model Autocomplete

`lavaangui` relies on `lavaan` to augment the model specified by you such that it can be fit. Thus, almost always, the model you draw is not exactly the model that will be fitted. Before fitting the model, I thus recommend that you inspect the model that actually will be fit. You can do this by pressing the button `Show Full Model` in the bottom toolbar. In the resulting model, paths that are added or modified by `lavaan` are displayed as dashed lines.

You can control what is added to your model via the `Automatically..` menu. 