---
title: Inspecting Results
---

The parameter estimates are automatically shown in the path diagram after the model has been fitted. You can change what is displayed in the `View Menu`. The remaining results are displayed in the `Results Window`. 

## View Menu

In the `View Menu`, you can modify how the model is displayed. First, you can toggle `Arrows Created by Lavaan` and `Variance Arrows` on or off. Second, you can decide whether to show `Standardized Estimates` or not. Third, you can select what estimates should be displayed: `Estimate` only, `Confidence Interval`, `Estimate + p-values`, or `Estimate + Standard Error`.

## Results Window

In the `Results Window`, all other results are shown. The first section under `$summary` contains the model summary by `lavaan`. See the [lavaan documentation](https://lavaan.ugent.be/tutorial/cfa.html) for an explanation. The second section under `$estimates` contains the parameter estimates in the form of a table. See the [lavaan documentation](https://lavaan.ugent.be/tutorial/inspect.html) for an explanation of the table.
