project:
  type: website
  output-dir: docs


website:
  title: "docs.lavaangui.org"



  navbar:
    background: secondary
    search: true
    left:
      - text: "Documentation"
        file: tutorial/overview.qmd
      - text: "Contribute"
        file: contribute.qmd
      
  sidebar:
    - title: "Tutorial"
      style: "docked"
      background: light
      contents:
        - tutorial/overview.qmd
        - tutorial/loading_data.qmd
        - tutorial/model_specification.qmd
        - tutorial/fitting.qmd
        - tutorial/result.qmd
        - tutorial/appearance.qmd
        - tutorial/save.qmd
        - tutorial/before.qmd
        - tutorial/help.qmd

        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
