project:
  type: website
  output-dir: docs


website:
  title: "docs.lavaangui.org"



  navbar:
    background: secondary
    search: true
    left:
      - text: "Documentation"
        file: tutorial/basic.qmd
      - text: "Contribute"
        href: https://github.com/karchjd/lavaangui/blob/main/CONTRIBUTING.md
      
  sidebar:
    - title: "Tutorial"
      style: "docked"
      background: light
      contents:
        - tutorial/basic.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
